import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar/index';
import { ReactLenis, useLenis } from '@studio-freight/react-lenis'
import { useEffect, useRef } from 'react';
import SmoothScrolling from "@/components/SmoothScrolling";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
      return (
        <html lang="en">
      
      <body className={inter.className}>
        <Navbar/>
        <SmoothScrolling >
        {children}
        </SmoothScrolling>
       
        </body>
    </html>
  )
}
